### ISSUE TITLE
Comparison with revproxyry?

### ISSUE THREAD

**Issue by mristin** [monkeydioude/capybara#2]
Hi!
I saw your post on reddit. Do you mind comparing your proxy against https://github.com/Parquery/revproxyry in the readme? (Disclosure: I'm the main contributor of revproxyry.)

**Comment by monkeydioude** [comment]
Hello mristin,

I'm not able to give a correct answer at the moment as I don't know what I will be doing with this project in the future. I will think about it more thoroughly in about 2 weeks (after vacations are over 😎).

**Comment by monkeydioude** [comment]
Update: vacations are over (:sunglasses:), I started school and still haven't done the comparison. Really sorry about this...
